#CodeEmailMKT.Domain.Entity.User.dcm.yml
CodeEmailMKT\Domain\Entity\User:
  type: entity
  #repositoryClass: CodeEmailMKT\Infrastructure\Persistence\Doctrine\Repository\UserRepository
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    email:
      type: string
      unique: true
      length: 255
      options:
        fixed: true
        comment: User's email address
    password:
      type: string
      length: 60
  lifecycleCallbacks:
    prePersist: [generatePassword]
